// Code generated by cmd/genprices; DO NOT EDIT.
// Source: internal/router/catalog (USD per 1M tokens).

export interface ModelPricing {
	inputUsdPerMillion: number;
	outputUsdPerMillion: number;
	cacheReadMultiplier: number;
}

export const PRICING_VERSION = "catalog-sha256:ea3eea30ac0bd712";

export const MODEL_PRICING: Readonly<Record<string, ModelPricing>> = Object.freeze({
	"deepseek-ai/deepseek-v4-flash": { inputUsdPerMillion: 0.15, outputUsdPerMillion: 0.25, cacheReadMultiplier: 0.5333333333333333 },
	"deepseek-ai/deepseek-v4-pro": { inputUsdPerMillion: 1, outputUsdPerMillion: 2.5, cacheReadMultiplier: 0.25 },
	"deepseek-ai/deepseek-v4.1-flash": { inputUsdPerMillion: 0.3, outputUsdPerMillion: 0.6, cacheReadMultiplier: 0.06666666666666667 },
	"moonshotai/kimi-k3": { inputUsdPerMillion: 3, outputUsdPerMillion: 12.5, cacheReadMultiplier: 0.16666666666666666 },
	"motif-technologies/motif-3": { inputUsdPerMillion: 0.5, outputUsdPerMillion: 2, cacheReadMultiplier: 0.4 },
	"qwen/qwen3.8-27b": { inputUsdPerMillion: 0.4, outputUsdPerMillion: 3, cacheReadMultiplier: 0.5 },
	"zai-org/glm-5.3": { inputUsdPerMillion: 1, outputUsdPerMillion: 4, cacheReadMultiplier: 0.3 },
	"zai-org/glm-5.3-flash": { inputUsdPerMillion: 0.15, outputUsdPerMillion: 0.5, cacheReadMultiplier: 0.2 },
});
