// Code generated by cmd/genprices; DO NOT EDIT.
// Source: internal/router/catalog (USD per 1M tokens).

export interface ModelPricing {
	inputUsdPerMillion: number;
	outputUsdPerMillion: number;
}

export const PRICING_VERSION = "catalog-sha256:50d0f712b968277a";

export const MODEL_PRICING: Readonly<Record<string, ModelPricing>> = Object.freeze({
	"deepseek-ai/deepseek-v4-flash": { inputUsdPerMillion: 0.15, outputUsdPerMillion: 0.25 },
	"deepseek-ai/deepseek-v4-pro": { inputUsdPerMillion: 1, outputUsdPerMillion: 2.5 },
	"google/gemma-4-31b-it": { inputUsdPerMillion: 0.2, outputUsdPerMillion: 0.5 },
	"moonshotai/kimi-k2.7": { inputUsdPerMillion: 0.75, outputUsdPerMillion: 3.5 },
	"moonshotai/kimi-k3": { inputUsdPerMillion: 3, outputUsdPerMillion: 12.5 },
	"motif-technologies/motif-3": { inputUsdPerMillion: 0.5, outputUsdPerMillion: 2 },
	"openai/gpt-oss-120b": { inputUsdPerMillion: 0.15, outputUsdPerMillion: 0.6 },
	"qwen/qwen3.6-27b": { inputUsdPerMillion: 0.32, outputUsdPerMillion: 3.2 },
	"z-ai/glm-5.2": { inputUsdPerMillion: 1, outputUsdPerMillion: 4 },
});
