// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"
)

const getAccountByAiandUserID = `-- name: GetAccountByAiandUserID :one
SELECT id, aiand_user_id, aiand_organization_id, display_name, created_at, last_login_at, deleted_at
FROM router.accounts
WHERE aiand_user_id = $1::varchar
  AND deleted_at IS NULL
`

// Login lookup, active only. Used when a returning user logs back in with a
// (new) aiand key that resolves to the same aiand user id.
//
//	SELECT id, aiand_user_id, aiand_organization_id, display_name, created_at, last_login_at, deleted_at
//	FROM router.accounts
//	WHERE aiand_user_id = $1::varchar
//	  AND deleted_at IS NULL
func (q *Queries) GetAccountByAiandUserID(ctx context.Context, aiandUserID string) (RouterAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByAiandUserID, aiandUserID)
	var i RouterAccount
	err := row.Scan(
		&i.ID,
		&i.AiandUserID,
		&i.AiandOrganizationID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, aiand_user_id, aiand_organization_id, display_name, created_at, last_login_at, deleted_at
FROM router.accounts
WHERE id = $1::varchar
  AND deleted_at IS NULL
`

// Session verification loads the account by its router-generated id.
//
//	SELECT id, aiand_user_id, aiand_organization_id, display_name, created_at, last_login_at, deleted_at
//	FROM router.accounts
//	WHERE id = $1::varchar
//	  AND deleted_at IS NULL
func (q *Queries) GetAccountByID(ctx context.Context, id string) (RouterAccount, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i RouterAccount
	err := row.Scan(
		&i.ID,
		&i.AiandUserID,
		&i.AiandOrganizationID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE router.accounts
SET deleted_at = NOW()
WHERE id = $1::varchar
  AND deleted_at IS NULL
`

// Soft-delete an account (wipe on key revocation). Keeps the row so audit
// trails survive; the user re-presents a fresh aiand key to re-instantiate.
//
//	UPDATE router.accounts
//	SET deleted_at = NOW()
//	WHERE id = $1::varchar
//	  AND deleted_at IS NULL
func (q *Queries) SoftDeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteAccount, id)
	return err
}

const upsertAccount = `-- name: UpsertAccount :one
INSERT INTO router.accounts (
    id,
    aiand_user_id,
    aiand_organization_id,
    display_name
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    $4::varchar
)
ON CONFLICT (aiand_user_id) WHERE deleted_at IS NULL DO UPDATE SET
    last_login_at          = NOW(),
    aiand_organization_id  = EXCLUDED.aiand_organization_id,
    display_name           = COALESCE(EXCLUDED.display_name, router.accounts.display_name)
RETURNING id, aiand_user_id, aiand_organization_id, display_name, created_at, last_login_at, deleted_at
`

type UpsertAccountParams struct {
	ID                  string
	AiandUserID         string
	AiandOrganizationID string
	DisplayName         *string
}

// Upsert is a no-op when the aiand user already has an active account, and a
// fresh INSERT (with the caller-generated id, which doubles as the
// installation external_id) when they don't. On returning login it bumps
// last_login_at, refreshes aiand_organization_id, and updates display_name
// only if a new one was given (COALESCE so a login from a client that omits
// display_name can't blank an existing value). Concurrency: two concurrent
// first-logins for the same aiand user collide on the partial unique index;
// the loser's INSERT is diverted to the DO UPDATE and returns the WINNER's row,
// so both callers agree on one account id and, therefore, one installation.
//
//	INSERT INTO router.accounts (
//	    id,
//	    aiand_user_id,
//	    aiand_organization_id,
//	    display_name
//	)
//	VALUES (
//	    $1::varchar,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::varchar
//	)
//	ON CONFLICT (aiand_user_id) WHERE deleted_at IS NULL DO UPDATE SET
//	    last_login_at          = NOW(),
//	    aiand_organization_id  = EXCLUDED.aiand_organization_id,
//	    display_name           = COALESCE(EXCLUDED.display_name, router.accounts.display_name)
//	RETURNING id, aiand_user_id, aiand_organization_id, display_name, created_at, last_login_at, deleted_at
func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) (RouterAccount, error) {
	row := q.db.QueryRow(ctx, upsertAccount,
		arg.ID,
		arg.AiandUserID,
		arg.AiandOrganizationID,
		arg.DisplayName,
	)
	var i RouterAccount
	err := row.Scan(
		&i.ID,
		&i.AiandUserID,
		&i.AiandOrganizationID,
		&i.DisplayName,
		&i.CreatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}
