// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveAccountSessionByHash = `-- name: GetActiveAccountSessionByHash :one
SELECT id, account_id, token_hash, token_prefix, token_suffix, issued_at, expires_at, revoked_at, last_seen_at, ip_at_issue, installation_id
FROM router.account_sessions
WHERE token_hash = $1::varchar
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

// Active-session lookup by token hash. Returns a row only while the session is
// live (not revoked, not expired).
//
//	SELECT id, account_id, token_hash, token_prefix, token_suffix, issued_at, expires_at, revoked_at, last_seen_at, ip_at_issue, installation_id
//	FROM router.account_sessions
//	WHERE token_hash = $1::varchar
//	  AND revoked_at IS NULL
//	  AND expires_at > NOW()
func (q *Queries) GetActiveAccountSessionByHash(ctx context.Context, tokenHash string) (RouterAccountSession, error) {
	row := q.db.QueryRow(ctx, getActiveAccountSessionByHash, tokenHash)
	var i RouterAccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.TokenSuffix,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.IpAtIssue,
		&i.InstallationID,
	)
	return i, err
}

const insertAccountSession = `-- name: InsertAccountSession :one
INSERT INTO router.account_sessions (
    account_id,
    installation_id,
    token_hash,
    token_prefix,
    token_suffix,
    expires_at,
    ip_at_issue
)
VALUES (
    $1::varchar,
    $2::varchar,
    $3::varchar,
    $4::varchar,
    $5::varchar,
    $6::timestamptz,
    $7::inet
)
RETURNING id, account_id, token_hash, token_prefix, token_suffix, issued_at, expires_at, revoked_at, last_seen_at, ip_at_issue, installation_id
`

type InsertAccountSessionParams struct {
	AccountID      string
	InstallationID *string
	TokenHash      string
	TokenPrefix    string
	TokenSuffix    string
	ExpiresAt      pgtype.Timestamptz
	IpAtIssue      *netip.Addr
}

// Mints a new session row for an account. token_hash is the SHA-256 of the
// opaque cookie value; token_prefix/token_suffix are the safe 8+4 display parts.
// installation_id is the tenant row resolved at login.
//
//	INSERT INTO router.account_sessions (
//	    account_id,
//	    installation_id,
//	    token_hash,
//	    token_prefix,
//	    token_suffix,
//	    expires_at,
//	    ip_at_issue
//	)
//	VALUES (
//	    $1::varchar,
//	    $2::varchar,
//	    $3::varchar,
//	    $4::varchar,
//	    $5::varchar,
//	    $6::timestamptz,
//	    $7::inet
//	)
//	RETURNING id, account_id, token_hash, token_prefix, token_suffix, issued_at, expires_at, revoked_at, last_seen_at, ip_at_issue, installation_id
func (q *Queries) InsertAccountSession(ctx context.Context, arg InsertAccountSessionParams) (RouterAccountSession, error) {
	row := q.db.QueryRow(ctx, insertAccountSession,
		arg.AccountID,
		arg.InstallationID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.TokenSuffix,
		arg.ExpiresAt,
		arg.IpAtIssue,
	)
	var i RouterAccountSession
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.TokenSuffix,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastSeenAt,
		&i.IpAtIssue,
		&i.InstallationID,
	)
	return i, err
}

const listAccountSessionsForAccount = `-- name: ListAccountSessionsForAccount :many
SELECT id, account_id, token_hash, token_prefix, token_suffix, issued_at, expires_at, revoked_at, last_seen_at, ip_at_issue, installation_id
FROM router.account_sessions
WHERE account_id = $1::varchar
ORDER BY issued_at DESC
`

// Session index for "my sessions" dashboard UI.
//
//	SELECT id, account_id, token_hash, token_prefix, token_suffix, issued_at, expires_at, revoked_at, last_seen_at, ip_at_issue, installation_id
//	FROM router.account_sessions
//	WHERE account_id = $1::varchar
//	ORDER BY issued_at DESC
func (q *Queries) ListAccountSessionsForAccount(ctx context.Context, accountID string) ([]RouterAccountSession, error) {
	rows, err := q.db.Query(ctx, listAccountSessionsForAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RouterAccountSession
	for rows.Next() {
		var i RouterAccountSession
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.TokenSuffix,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastSeenAt,
			&i.IpAtIssue,
			&i.InstallationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccountSessionByID = `-- name: RevokeAccountSessionByID :execrows
UPDATE router.account_sessions
SET revoked_at = NOW()
WHERE account_id = $1::varchar
  AND id = $2::uuid
  AND revoked_at IS NULL
`

type RevokeAccountSessionByIDParams struct {
	AccountID string
	ID        uuid.UUID
}

// Revoke one session (logout). Scoped to the account to prevent cross-account
// revocation.
//
//	UPDATE router.account_sessions
//	SET revoked_at = NOW()
//	WHERE account_id = $1::varchar
//	  AND id = $2::uuid
//	  AND revoked_at IS NULL
func (q *Queries) RevokeAccountSessionByID(ctx context.Context, arg RevokeAccountSessionByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccountSessionByID, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllAccountSessionsForAccount = `-- name: RevokeAllAccountSessionsForAccount :execrows
UPDATE router.account_sessions
SET revoked_at = NOW()
WHERE account_id = $1::varchar
  AND revoked_at IS NULL
`

// Revoke every session for an account ("logout everywhere"; also called during
// account wipe).
//
//	UPDATE router.account_sessions
//	SET revoked_at = NOW()
//	WHERE account_id = $1::varchar
//	  AND revoked_at IS NULL
func (q *Queries) RevokeAllAccountSessionsForAccount(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllAccountSessionsForAccount, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAccountSessionLastSeen = `-- name: TouchAccountSessionLastSeen :execrows
UPDATE router.account_sessions
SET last_seen_at = NOW()
WHERE account_id = $1::varchar
  AND id = $2::uuid
`

type TouchAccountSessionLastSeenParams struct {
	AccountID string
	ID        uuid.UUID
}

// Bump last_seen_at when the middleware validates a live session (cheap write,
// throttled to once per request).
//
//	UPDATE router.account_sessions
//	SET last_seen_at = NOW()
//	WHERE account_id = $1::varchar
//	  AND id = $2::uuid
func (q *Queries) TouchAccountSessionLastSeen(ctx context.Context, arg TouchAccountSessionLastSeenParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchAccountSessionLastSeen, arg.AccountID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
