#!/usr/bin/env python3
"""Build artifacts/v0.76: additive overlay of the 13-model AIand roster on
FROZEN v0.75 geometry (v0.70/v0.75 precedent — see v0.75/metadata.yaml changelog).

- centroids.bin copied BYTE-IDENTICAL from v0.75 (no retrain, no re-cluster).
- The 18 existing v0.75 models are KEPT; the 13 AIand models are ADDED. A
  default bundle that dropped non-AIand models would break every other deploy
  on the version bump. AIand-only deploys narrow the pool at boot via
  availableProviders (only AIAND_API_KEY wired -> filterByProviders drops the
  rest).
- Quality columns for the new models are cloned from the semantically nearest
  existing column, scaled, and clamped to the cluster's existing [min,max].
  Mapping below (same table lands in the metadata changelog).
- model_axes rows: AIand catalog prices (live-probed GET /v1/models,
  2026-10-04, USD/1M -> per-1k); TTFT/TPS/verbosity cloned from the source
  model's axes row (documented as cloned, pending live measurement).
- rankings.json regenerated by the EXACT runtime blend (blendScoresV2 at
  uniform alpha=0.96, speed_weight=0, output_cost_ratio=0 -- the formula that
  reproduces v0.75's committed rankings bit-for-bit; parity is asserted here
  before regenerating).
- model_features.json rebuilt as the model-centric repackage of
  quality_means + model_axes (the loader prefers it over both files, so they
  must stay consistent).
- latest pointer is NOT touched: promotion is a separate deliberate step.

Usage: python scripts/build_v076_aiand_roster.py
Requires: PyYAML (metadata round-trip). Deterministic: re-running reproduces
byte-identical output.
"""

import hashlib
import json
import shutil
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "internal" / "router" / "cluster" / "artifacts"
SRC = ART / "v0.75"
DST = ART / "v0.76"

# AIand model -> (clone source column = existing v0.75 model, scale, note).
# Prices are live-probed USD/1M in/out (plan .context/aiand-router-plan.md §1),
# converted to per-1k below.
AIAND_ROSTER = [
    # model                              source                          scale  in/1M  out/1M  note
    ("zai-org/glm-5.2", "z-ai/glm-5.2", 1.00, 1.00, 4.00,
     "Same weights as the deployed z-ai/glm-5.2, served by AIand; column cloned directly."),
    ("zai-org/glm-5.3", "z-ai/glm-5.2", 1.00, 1.00, 4.00,
     "glm-5.3 day-0 on AIand, no labels yet; clone glm-5.2 (immediate predecessor, same tier/price)."),
    ("zai-org/glm-5.3-flash", "z-ai/glm-5.2", 0.85, 0.15, 0.50,
     "Flash tier of glm-5.3; clone glm-5.2 scaled 0.85 (day-0, no labels; $0.15/$0.50 lane)."),
    ("deepseek-ai/deepseek-v4-flash", "deepseek/deepseek-v4-flash", 1.00, 0.15, 0.25,
     "Same model family already on the roster (deepinfra-hosted); column cloned directly."),
    ("deepseek-ai/deepseek-v4.1-flash", "deepseek/deepseek-v4-flash", 1.00, 0.30, 0.60,
     "v4.1 is the newer flash (adds vision); no labels day-0; clone v4-flash column."),
    ("deepseek-ai/deepseek-v4-pro", "deepseek/deepseek-v4-pro", 1.00, 1.00, 2.50,
     "Same weights as the deployed deepseek-v4-pro (deepinfra-hosted); column cloned directly."),
    ("moonshotai/kimi-k2.7-code", "moonshotai/kimi-k2.7", 1.00, 0.75, 3.50,
     "kimi-k2.7 code variant; no separate labels day-0; clone kimi-k2.7 column."),
    ("moonshotai/kimi-k3", "moonshotai/kimi-k2.7", 1.05, 3.00, 12.50,
     "k3 is stronger than k2.7; clone kimi-k2.7 scaled 1.05, clamped to the cluster max."),
    ("qwen/qwen3.6-27b", "qwen/qwen3-coder-next", 0.92, 0.32, 3.20,
     "Day-0 27B coder; nearest labeled qwen coder column scaled 0.92 (smaller, cheaper tier)."),
    ("qwen/qwen3.8-27b", "qwen/qwen3-coder-next", 0.95, 0.40, 3.00,
     "Day-0 27B coder (newer than 3.6); clone qwen3-coder-next scaled 0.95."),
    ("motif-technologies/motif-3", "qwen/qwen3-coder-next", 0.88, 0.50, 2.00,
     "Unlabeled open-weight coder day-0; proxied onto qwen3-coder-next scaled 0.88."),
    ("google/gemma-4-31b-it", "qwen/qwen3-next-80b-a3b-instruct", 0.85, 0.20, 0.50,
     "Instruction-tuned generalist in the same size/price lane; clone qwen3-next-80b scaled 0.85."),
    ("openai/gpt-oss-120b", "qwen/qwen3-next-80b-a3b-instruct", 0.88, 0.15, 0.60,
     "Open-weights 120B instruct; nearest open-weight generalist column scaled 0.88."),
]

# Blend knobs of the committed rankings.json (v0.75 form; parity-gated below).
RANKINGS_ALPHA = 0.96


def load(name):
    with open(SRC / name, encoding="utf-8") as f:
        return json.load(f)


def dump(name, data):
    DST.mkdir(exist_ok=True)
    with open(DST / name, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def blend_row(qm_row, models, costs, alpha):
    """Exact runtime blend (Scorer.blendScoresV2) for one cluster at
    speed_weight=0 / output_cost_ratio=0: cost axis = input_per_1k only."""
    qmin, qmax = min(qm_row[m] for m in models), max(qm_row[m] for m in models)
    qr = qmax - qmin
    cmin, cmax = min(costs.values()), max(costs.values())
    cr = cmax - cmin
    out = {}
    for m in models:
        qn = (qm_row[m] - qmin) / qr if qr > 0 else 0.0
        cn = (costs[m] - cmin) / cr if cr > 0 else 0.0
        out[m] = alpha * qn + (1.0 - alpha) * (1.0 - cn)
    return out


def main():
    qm = load("quality_means.json")
    axes = load("model_axes.json")
    reg = load("model_registry.json")
    rk = load("rankings.json")

    old_models = sorted(qm["quality_means"]["0"].keys())
    assert len(old_models) == 18, "expected the v0.75 18-model roster"

    # --- parity gate: the committed v0.75 rankings are the runtime blend at
    # uniform alpha over the unchanged roster. Prove the formula before using it.
    costs_old = {m: (axes["axes"][m]["input_per_1k_usd"] or 0.0) for m in old_models}
    for k in range(16):
        got = blend_row(qm["quality_means"][str(k)], old_models, costs_old, RANKINGS_ALPHA)
        for m in old_models:
            assert abs(got[m] - rk["rankings"][str(k)][m]) < 1e-12, (
                f"v0.75 rankings parity failed at cluster {k} model {m}")

    new_names = [r[0] for r in AIAND_ROSTER]
    assert len(set(new_names)) == 13 and not set(new_names) & set(old_models)

    # --- quality_means: clone + scale, clamped to the cluster's existing range.
    for k in range(16):
        row = qm["quality_means"][str(k)]
        lo, hi = min(row.values()), max(row.values())
        for name, src, scale, _in, _out, _note in AIAND_ROSTER:
            row[name] = min(hi, max(lo, row[src] * scale))

    # --- model_axes: real catalog prices, cloned latency/verbosity.
    for name, src, _scale, in_1m, out_1m, _note in AIAND_ROSTER:
        src_ax = axes["axes"][src]
        axes["axes"][name] = {
            "input_per_1k_usd": in_1m / 1000.0,
            "output_per_1k_usd": out_1m / 1000.0,
            "tps": src_ax["tps"],
            "ttft_s": src_ax["ttft_s"],
            "verbosity_tokens": src_ax["verbosity_tokens"],
        }

    # --- rankings: regenerate over the full 31-model roster.
    models = sorted(old_models + new_names)
    costs = {m: (axes["axes"][m]["input_per_1k_usd"] or 0.0) for m in models}
    rk["rankings"] = {
        str(k): blend_row(qm["quality_means"][str(k)], models, costs, RANKINGS_ALPHA)
        for k in range(16)
    }
    rk["meta"]["n_models"] = len(models)

    # --- model_registry: 13 proxy entries (bench_column = clone source column).
    bench_by_model = {e["model"]: e["bench_column"] for e in reg["deployed_models"]}
    for name, src, _scale, _in, _out, note in AIAND_ROSTER:
        reg["deployed_models"].append({
            "model": name,
            "provider": "aiand",
            "bench_column": bench_by_model[src],
            "proxy": True,
            "proxy_note": note,
        })
    reg["meta"]["comment"] = (
        "v0.76: v0.75 18-model roster + 13 AIand models (frozen-geometry additive overlay, "
        "scripts/build_v076_aiand_roster.py). AIand columns are clones/scales of nearest "
        "existing columns; priced at live-probed AIand catalog rates. AIand-only deploys "
        "narrow via availableProviders at boot.")
    reg["meta"]["last_refreshed"] = "2026-10-04"
    reg["meta"]["parent"] = "v0.75"

    DST.mkdir(exist_ok=True)
    shutil.copyfile(SRC / "centroids.bin", DST / "centroids.bin")
    features = {
        "meta": {
            "comment": "v0.76: v0.75 geometry + 13 AIand clones/scales (build_v076_aiand_roster.py).",
            "k": 16,
            "n_models": len(models),
            "roster_version": "v0.76",
            "source": "quality_means.json + model_axes.json",
        },
        "models": {
            m: {
                "psi_probe": [qm["quality_means"][str(k)][m] for k in range(16)],
                "operational": axes["axes"][m],
            } for m in models
        },
    }

    # --- metadata.yaml
    with open(SRC / "metadata.yaml", encoding="utf-8") as f:
        meta = yaml.safe_load(f)
    meta["version"] = "v0.76"
    meta["parent"] = "v0.75"
    meta["deployed_models"] = meta["deployed_models"] + new_names
    meta["deployed_providers"] = sorted(set(meta["deployed_providers"]) | {"aiand"})
    for name, _src, _scale, in_1m, _out, _note in AIAND_ROSTER:
        meta["cost_per_1k_input_usd"][name] = in_1m / 1000.0
    clone_lines = "; ".join(
        f"{n}={s}" + ("" if sc == 1.0 else f"×{sc:g}")
        for n, s, sc, *_ in AIAND_ROSTER)
    meta["changelog"] = (
        "v0.76 = v0.75 with the 13-model AIand roster ADDED (additive overlay; no model retired). "
        "centroids.bin BYTE-IDENTICAL to v0.75 (no retrain, no re-cluster; K=16 geometry frozen). "
        "Each AIand model's quality_means column is a clone of the semantically nearest existing "
        f"column, scaled and clamped to the cluster's existing [min,max]: {clone_lines}. "
        "model_axes rows carry live-probed AIand catalog input/output prices (GET /v1/models, "
        "2026-10-04); TTFT/TPS/verbosity are cloned from the source model's axes row, pending live "
        "measurement. rankings.json regenerated by the exact runtime blend (uniform alpha=0.96, "
        "speed_weight=0, output_cost_ratio=0) over the 31-model roster — parity-gated: the same "
        "blend reproduces v0.75's committed rankings bit-for-bit on the unchanged 18-model roster "
        "first. The default roster keeps all 18 v0.75 models so non-AIand deploys are unaffected "
        "on bump; AIand-only deploys narrow via availableProviders at boot (only AIAND_API_KEY "
        "wired -> filterByProviders keeps the provider:\"aiand\" entries). Generated by "
        "scripts/build_v076_aiand_roster.py. Candidate; artifacts/latest NOT bumped (promotion is "
        "a separate deliberate step).\n\n" + meta["changelog"])
    with open(DST / "metadata.yaml", "w", encoding="utf-8", newline="\n") as f:
        yaml.safe_dump(meta, f, sort_keys=False, allow_unicode=True, width=100)

    # --- centroids: byte copy + hash verify
    h = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()  # noqa: E731
    assert h(SRC / "centroids.bin") == h(DST / "centroids.bin"), "centroids drift"

    dump("quality_means.json", qm)
    dump("model_axes.json", axes)
    dump("rankings.json", rk)
    dump("model_registry.json", reg)
    dump("model_features.json", features)

    print("wrote", DST)
    print("roster:", len(models), "models (", len(old_models), "+", len(new_names), ")")
    print("centroids sha256:", h(DST / "centroids.bin"))


if __name__ == "__main__":
    main()
